/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Banner, ConteudoSinalizadoEvent, IdentificadorOpcaoMenu, MenuBannerAlteradoEvent, OpcaoMenu, OpcaoMenuSelecionadaEvent } from "./components/app/app.interfaces";
import { Tamanho } from "./components/comuns/avatar/avatar.interfaces";
import { LogoutEvent } from "./components/conta-usuario/conta-usuario.interfaces";
import { AuthorizationConfig } from "./global/interfaces";
import { MenuHorizontalSelecionadoEvent } from "./components/app/menu-horizontal-item/menu-horizontal-item.interfaces";
import { PainelLateralShowEvent } from "./components/app/menu-painel-lateral/menu-painel-lateral.interfaces";
import { MenuVerticalSelecionadoEvent } from "./components/app/menu-vertical-item/menu-vertical-item.interfaces";
import { NotificacaoComLinkEvent, NotificacaoEvent, NotificacaoLink, TipoNotificacao } from "./components/notificacoes/notificacoes.interfaces";
import { NovidadeLeituraEvent } from "./components/novidades/novidades.interfaces";
import { ItemSelecaoContexto } from "./components/comuns/selecao-contexto/selecao-contexto.interfaces";
import { BlipChatUserInfo } from "./components/suporte/suporte.interfaces";
import { OpcaoUtilitarioSelecionadaEvent, Utilitario } from "./components/utilitarios/utilitarios.interfaces";
export { Banner, ConteudoSinalizadoEvent, IdentificadorOpcaoMenu, MenuBannerAlteradoEvent, OpcaoMenu, OpcaoMenuSelecionadaEvent } from "./components/app/app.interfaces";
export { Tamanho } from "./components/comuns/avatar/avatar.interfaces";
export { LogoutEvent } from "./components/conta-usuario/conta-usuario.interfaces";
export { AuthorizationConfig } from "./global/interfaces";
export { MenuHorizontalSelecionadoEvent } from "./components/app/menu-horizontal-item/menu-horizontal-item.interfaces";
export { PainelLateralShowEvent } from "./components/app/menu-painel-lateral/menu-painel-lateral.interfaces";
export { MenuVerticalSelecionadoEvent } from "./components/app/menu-vertical-item/menu-vertical-item.interfaces";
export { NotificacaoComLinkEvent, NotificacaoEvent, NotificacaoLink, TipoNotificacao } from "./components/notificacoes/notificacoes.interfaces";
export { NovidadeLeituraEvent } from "./components/novidades/novidades.interfaces";
export { ItemSelecaoContexto } from "./components/comuns/selecao-contexto/selecao-contexto.interfaces";
export { BlipChatUserInfo } from "./components/suporte/suporte.interfaces";
export { OpcaoUtilitarioSelecionadaEvent, Utilitario } from "./components/utilitarios/utilitarios.interfaces";
export namespace Components {
    interface BthAjuda {
        /**
          * URL para a home da central de ajuda. Por padrão irá obter do env.js
         */
        "centralAjudaHome"?: string;
    }
    /**
     * Permite configurar opções de navegação nos modelos de menu horizontal e vertical.
     * Possui áreas pré-definidas que permite compor as aplicações.
     */
    interface BthApp {
        /**
          * Permite definir um banner que é exibido acima do menu
         */
        "banner"?: Banner;
        /**
          * Permite customizar a cor de fundo da barra do menu. Por padrão segue a cor da linha dos produtos.
         */
        "menuBgColor": string;
        /**
          * Define se as opções do menu serão exibidas no formato "vertical", caso contrário serão exibidas no formato "horizontal"
          * @default false
         */
        "menuVertical"?: boolean;
        /**
          * Opções de navegação do menu
          * @default []
         */
        "opcoes"?: Array<OpcaoMenu>;
        /**
          * Opções de navegação a serem exibidas no header, ao lado da marca. Funciona de forma independente da navegação principal, e somente se o menu for vertical.
          * @default []
         */
        "opcoesHeader"?: Array<OpcaoMenu>;
        /**
          * Define o estado de ativo para o badge no icone do item do menu
          * @param identificador Identificador do menu
          * @param ativo boolean que indica se deve ou não mostrar
         */
        "setBadgeIcone": (identificador: IdentificadorOpcaoMenu, ativo: boolean) => Promise<void>;
        /**
          * Define o valor do contador de um item do menu
          * @param identificador Identificador do item do menu
          * @param valor Valor do contador
         */
        "setContadorMenu": (identificador: IdentificadorOpcaoMenu, valor: number) => Promise<void>;
        /**
          * Define o estado de ativo para o menu do parâmetro
          * @param identificador Identificador do menu
         */
        "setMenuAtivo": (identificador: IdentificadorOpcaoMenu) => Promise<void>;
    }
    /**
     * Este componente exibe um avatar
     */
    interface BthAvatar {
        /**
          * Define se o avatar possui borda
          * @default false
         */
        "borda"?: boolean;
        /**
          * Define a cor da borda
          * @default 'white'
         */
        "bordaCor"?: string;
        /**
          * Define o raio da borda do avatar. Caso informado, sobrescreve o atributo utilitario 'quadrado'.
          * @default '50%'
         */
        "bordaRaio"?: string;
        /**
          * Define o tamanho da borda
          * @default '1px'
         */
        "bordaTamanho"?: string;
        /**
          * Permite definir a dimensão (largura, altura) em px para o avatar
         */
        "dimensao"?: number;
        /**
          * Define um avatar de ícone conforme biblioteca `"Material Design Icons"`
         */
        "icone"?: string;
        /**
          * Define avatar do tipo iniciais, aceitando até 3 iniciais ou computando as iniciais automaticamente conforme palavras passadas
         */
        "iniciais"?: string;
        /**
          * Define se o avatar terá suas bordas no formato quadrado.  Por padrão é redondo
          * @default false
         */
        "quadrado"?: boolean;
        /**
          * Define a fonte de um avatar de imagem. Aceita imagem e svg.
         */
        "src"?: string;
        /**
          * Define um sub-ícone conforme biblioteca `"Material Design Icons"`
         */
        "subIcone"?: string;
        /**
          * Define o "title" do subícone
          * @default ''
         */
        "subIconeTitle": string;
        /**
          * Define o tamanho conforme dimensões pre-definidas para o avatar.  Opções disponíveis: menor (24x24), pequeno (28x28), medio (48x48) e grande (94x94)
          * @default 'medio'
         */
        "tamanho"?: Tamanho;
    }
    /**
     * Este componente exibe informações relacionadas ao usuário/conta logada
     * Este componente foi elaborado para comportar o slot "menu_ferramentas"
     */
    interface BthContaUsuario {
        /**
          * URL para home da Central de Usuários. Por padrão irá obter do env.js.
         */
        "centralUsuarioHome"?: string;
        /**
          * URL para foto de avatar do usuário
         */
        "fotoUrl": string;
        /**
          * Nome do usuário
         */
        "nome": string;
        /**
          * Usuário ("username" ou "email")
         */
        "usuario": string;
    }
    interface BthEmptyState {
        /**
          * Define se o empty state é para conexão offline
          * @default false
         */
        "offline": boolean;
        /**
          * Define se o empty state é para conexão online
          * @default false
         */
        "online": boolean;
        /**
          * Define se o empty state é para página não encontrada
          * @default false
         */
        "paginaNaoEncontrada": boolean;
        /**
          * Define se o empty state é de tamanho pequeno
          * @default false
         */
        "pequeno": boolean;
        /**
          * Define se o empty state é para registros
          * @default false
         */
        "registros": boolean;
        /**
          * Define se o empty state é para registros com pesquisa
          * @default false
         */
        "registrosPesquisa": boolean;
        /**
          * Define se o empty state está visível
          * @default false
         */
        "show": boolean;
    }
    interface BthIcone {
        /**
          * Especifica o label a ser utilizado para acessibilidade. Por padrão irá assumir o nome do ícone.
         */
        "ariaLabel": string | null;
        /**
          * Cor de preenchimento, no mesmo formato do `"color"` em CSS. Por padrão irá herdar do contexto inserido.
          * @default 'inherit'
         */
        "cor"?: string;
        /**
          * Identificador do ícone conforme biblioteca `"Material Design Icons"`
         */
        "icone": string;
        /**
          * Tamanho em pixels, no mesmo formato do `"font-size"` em CSS. Por padrão irá herdar do contexto inserido.
          * @default 'inherit'
         */
        "tamanho": string;
    }
    /**
     * Loader padrão com efeitos de animações
     */
    interface BthLoader {
        /**
          * Define se o loader é inline
          * @default false
         */
        "inline": boolean;
    }
    /**
     * Este componente exibe o logo da Betha e o nome do produto
     * Este componente foi elaborado para comportar o slot de "menu_marca_produto"
     */
    interface BthMarcaProduto {
        /**
          * Define a área de produtos.
         */
        "area"?: string;
        /**
          * Configuração de autorização. É necessária para o componente poder se autentizar com os serviços.
         */
        "authorization": AuthorizationConfig;
        /**
          * Define se o componente exibirá os produtos, condicionando a busca. Caso informado `false` não irá buscar por produtos.
          * @default false
         */
        "exibirProdutos"?: boolean;
        /**
          * Nome do produto
         */
        "produto": string;
        /**
          * URL para a home da betha store. Por padrão irá obter do env.js
         */
        "storeHome"?: string;
        /**
          * URL para home da suite de usuários. Por padrão irá obter do env.js
         */
        "suiteHome"?: string;
        /**
          * URL para a API de user accounts. Por padrão irá obter do env.js
         */
        "userAccountsApi"?: string;
    }
    /**
     * Facilita a criação de Ferramentas para o menu. Abstrai comportamentos responsivos e controle do painel lateral.
     */
    interface BthMenuFerramenta {
        /**
          * Descrição
          * @default ''
         */
        "descricao": string;
        /**
          * Fecha os paineis abertos
         */
        "fecharPaineisAbertos": () => Promise<void>;
        /**
          * Título do Painel Lateral
         */
        "tituloPainelLateral": string;
    }
    /**
     * Abstrai a estilização de um ícone para menu-ferramenta.
     * Também implementa a possibilidade de exibição de um `badge` ao lado do ícone, através da propriedade `contador`.
     */
    interface BthMenuFerramentaIcone {
        /**
          * Valor que será exibido em uma "badge" próximo ao ícone
          * @default 0
         */
        "contador": number;
        /**
          * Ícone conforme biblioteca `"Material Design Icons"`
          * @default 'cloud'
         */
        "icone": string;
        /**
          * Define se a estilização é "mobile". Por padrão é "desktop".
          * @default false
         */
        "mobile": boolean;
        /**
          * Badge de Status
         */
        "status": 'online' | 'offline' | undefined;
    }
    /**
     * Item que representa uma opção do menu para navegação horizontal
     */
    interface BthMenuHorizontalItem {
        /**
          * Está ativo?
         */
        "ativo": boolean;
        /**
          * Contador  Exibe o valor inforamdo em um badge próximo ao menu
         */
        "contador": number;
        /**
          * Descrição
         */
        "descricao": string;
        /**
          * Identificador
         */
        "identificador": IdentificadorOpcaoMenu;
        /**
          * Possui permissão?
          * @default true
         */
        "possuiPermissao": boolean;
    }
    /**
     * Possibilita incluir conteúdo dinâmico em um painel lateral que sobrepõe o conteúdo da tela pela direita
     */
    interface BthMenuPainelLateral {
        /**
          * Cancela o timeout de interação ativo caso exista
         */
        "cancelarAberturaComAnimacao": () => Promise<void>;
        /**
          * Fecha o painel lateral e emite evento para que outros sobrepostos sejam fechados.
         */
        "fecharPaineisAbertos": () => Promise<void>;
        /**
          * Alterna o estado em aberto do painel para o valor do parâmetro após um timeout padrão de interações
         */
        "setShowComAnimacao": (show: boolean) => Promise<void>;
        /**
          * Estado de visibilidade
          * @default false
         */
        "show": boolean;
        /**
          * Título que será exibido no cabeçalho
         */
        "titulo": string;
    }
    /**
     * Item que representa uma opção do menu para navegação vertical
     */
    interface BthMenuVerticalItem {
        /**
          * Está ativo?
         */
        "ativo": boolean;
        /**
          * Valor que será exibido em uma "badge" próximo ao menu
         */
        "contador": number;
        /**
          * Descrição
         */
        "descricao": string;
        /**
          * Ícone conforme biblioteca `"Material Design Icons"`
         */
        "icone": string;
        /**
          * Identificador
         */
        "identificador": IdentificadorOpcaoMenu;
        /**
          * Identificador do menu agrupador "pai"
         */
        "identificadorPai": IdentificadorOpcaoMenu;
        /**
          * O menu principal está recolhido?  Este parâmetro influência no formato como alguns elementos são exibidos, ex: badge do contador.
         */
        "menuLateralRecolhido": boolean;
        /**
          * Indica se deve aparecer um badge no ícone.
         */
        "possuiBadgeIcone": boolean;
        /**
          * Possui permissão?
          * @default true
         */
        "possuiPermissao": boolean;
        /**
          * Está recolhido?
         */
        "recolhido": boolean;
        /**
          * É um submenu?
         */
        "submenu": boolean;
        /**
          * Possui submenus?
         */
        "submenus"?: Array<OpcaoMenu>;
    }
    interface BthNavbarPillGroup {
        /**
          * Descrição
         */
        "descricao": string;
    }
    interface BthNavbarPillItem {
        /**
          * Está ativo?
          * @default false
         */
        "ativo": boolean;
        /**
          * Descrição
         */
        "descricao": string;
        /**
          * Ícone conforme biblioteca `"Material Design Icons"`
          * @default 'cloud-question'
         */
        "icone": string;
        /**
          * Identificador. É enviado no evento de click.
         */
        "identificador": any;
        /**
          * Exibir totalizador?
          * @default true
         */
        "showTotalizador": boolean;
        /**
          * Totalizador
          * @default 0
         */
        "totalizador": number;
    }
    interface BthNotificacaoItem {
        /**
          * Link acompanhar
         */
        "acompanharLink": NotificacaoLink;
        /**
          * Link cancelamento
         */
        "cancelamentoLink": NotificacaoLink;
        /**
          * Data e hora
         */
        "dataHora": number | string;
        /**
          * Ícone
         */
        "icone": string;
        /**
          * Identificador
         */
        "identificador": string;
        /**
          * Origem
         */
        "origem": string;
        /**
          * Percentual do progresso
         */
        "percentualProgresso": number;
        /**
          * Possui progresso?
         */
        "possuiProgresso": boolean;
        /**
          * Prioridade
         */
        "prioridade": number;
        /**
          * Link resultado
         */
        "resultadoLink": NotificacaoLink;
        /**
          * Status
         */
        "status": string;
        /**
          * Texto
         */
        "texto": string;
        /**
          * Tipo de notificação
         */
        "tipo": TipoNotificacao;
    }
    interface BthNotificacoes {
        /**
          * Configuração de autorização. É necessária para o componente poder realizar autentizar com os serviços.
         */
        "authorization": AuthorizationConfig;
        /**
          * URL para a api de notificações. Por padrão irá obter do env.js
         */
        "notificacoesApi"?: string;
        /**
          * URL para o channel websocket de notificações. Por padrão irá obter do env.js
         */
        "notificacoesWs"?: string;
    }
    interface BthNovidadeItem {
        /**
          * Data e hora
         */
        "dataHora": string;
        /**
          * Identificador
         */
        "identificador": string;
        /**
          * Define se já está lida
          * @default false
         */
        "isLida": boolean;
        /**
          * Mensagem
         */
        "mensagem": string;
        /**
          * Título
         */
        "titulo": string;
        /**
          * URL para obter mais informações
         */
        "url": string;
    }
    interface BthNovidades {
        /**
          * Configuração de autorização. É necessária para o componente poder realizar autentizar com os serviços.
         */
        "authorization": AuthorizationConfig;
        /**
          * URL para a api de novidades. Por padrão irá obter do env.js.
         */
        "novidadesApi"?: string;
    }
    interface BthPesquisa {
        /**
          * Configuração de autorização. É necessária para o componente poder autenticar com os serviços.
         */
        "authorization": AuthorizationConfig;
        /**
          * URL para a api de licenças. Por padrão irá obter do env.js.
         */
        "licencasApi"?: string;
        /**
          * URL para a api de pesquisas. Por padrão irá obter do env.js.
         */
        "pesquisaApi"?: string;
    }
    /**
     * Este componente permite compor uma lista de seleção de contexto.
     */
    interface BthSelecaoContexto {
        /**
          * Método para buscar os itens de seleção
         */
        "buscar": () => Promise<ItemSelecaoContexto[]>;
        /**
          * Placeholder para o input de pesquisa
         */
        "placeholderPesquisa"?: string;
        /**
          * Método executado ao selecionar algum item da lista
         */
        "selecionar": (item: ItemSelecaoContexto) => Promise<any> | void;
    }
    /**
     * Componente do menu Suporte com Blip Chat
     * @see https://gitlab.services.betha.cloud/ped/tecnologia/nlp/blip-webchat-loader
     * @see https://gitlab.services.betha.cloud/ped/suite/atendimento/components/suite-atendimento
     */
    interface BthSuporte {
        /**
          * Habilita ou desabilita o botão de abrir um chamado no atendimento
          * @default false
         */
        "atendimento": boolean;
        /**
          * Configuração de autorização. É necessária para o componente poder autenticar com os serviços.
         */
        "authorization": AuthorizationConfig;
        /**
          * Habilita ou desabilita o Blip Chat
          * @default false
         */
        "blipChat": boolean;
        /**
          * Usar estilos que este componente fornece
          * @default false
         */
        "blipChatCustomStyle": boolean;
        /**
          * Cor do botão flutuante do Blip Chat
         */
        "blipChatFabButtonColor": string;
        /**
          * Usuário de sessão do Blip Chat
         */
        "blipChatUserInfo": BlipChatUserInfo;
        /**
          * URL para a home da central de ajuda. Por padrão irá obter do env.js
         */
        "centralAjudaHome"?: string;
        /**
          * Indica se a aplicação já possui botão flutuante
          * @default false
         */
        "fabButton": boolean;
        /**
          * Método para testar recebimento de uma mensagem do window para definir o badge de mensagens não vistas, através de um evento do tipo 'BLIP_WEBCHAT_NOTIFICATION' emitido pelo loader do Blip Chat
          * @see https://gitlab.services.betha.cloud/ped/tecnologia/nlp/blip-webchat-loader
         */
        "handleWindowMessage": (data: any) => Promise<void>;
        /**
          * URL para a api de licenças. Por padrão irá obter do env.js.
         */
        "licencasApi"?: string;
        /**
          * Carrega o Blip Chat
         */
        "loadBlipChat": () => Promise<void>;
    }
    interface BthUtilitarios {
        /**
          * Utilitarios
         */
        "utilitarios": Array<Utilitario>;
    }
}
export interface BthAppCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthAppElement;
}
export interface BthAvatarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthAvatarElement;
}
export interface BthContaUsuarioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthContaUsuarioElement;
}
export interface BthMenuHorizontalItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthMenuHorizontalItemElement;
}
export interface BthMenuPainelLateralCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthMenuPainelLateralElement;
}
export interface BthMenuVerticalItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthMenuVerticalItemElement;
}
export interface BthNavbarPillItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthNavbarPillItemElement;
}
export interface BthNotificacaoItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthNotificacaoItemElement;
}
export interface BthNotificacoesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthNotificacoesElement;
}
export interface BthNovidadeItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthNovidadeItemElement;
}
export interface BthNovidadesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthNovidadesElement;
}
export interface BthUtilitariosCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBthUtilitariosElement;
}
declare global {
    interface HTMLBthAjudaElement extends Components.BthAjuda, HTMLStencilElement {
    }
    var HTMLBthAjudaElement: {
        prototype: HTMLBthAjudaElement;
        new (): HTMLBthAjudaElement;
    };
    interface HTMLBthAppElementEventMap {
        "bannerAlterado": MenuBannerAlteradoEvent;
        "opcaoMenuSelecionada": OpcaoMenuSelecionadaEvent;
        "botaoBannerAcionado": void;
    }
    /**
     * Permite configurar opções de navegação nos modelos de menu horizontal e vertical.
     * Possui áreas pré-definidas que permite compor as aplicações.
     */
    interface HTMLBthAppElement extends Components.BthApp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthAppElementEventMap>(type: K, listener: (this: HTMLBthAppElement, ev: BthAppCustomEvent<HTMLBthAppElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthAppElementEventMap>(type: K, listener: (this: HTMLBthAppElement, ev: BthAppCustomEvent<HTMLBthAppElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthAppElement: {
        prototype: HTMLBthAppElement;
        new (): HTMLBthAppElement;
    };
    interface HTMLBthAvatarElementEventMap {
        "imageLoadError": any;
    }
    /**
     * Este componente exibe um avatar
     */
    interface HTMLBthAvatarElement extends Components.BthAvatar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthAvatarElementEventMap>(type: K, listener: (this: HTMLBthAvatarElement, ev: BthAvatarCustomEvent<HTMLBthAvatarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthAvatarElementEventMap>(type: K, listener: (this: HTMLBthAvatarElement, ev: BthAvatarCustomEvent<HTMLBthAvatarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthAvatarElement: {
        prototype: HTMLBthAvatarElement;
        new (): HTMLBthAvatarElement;
    };
    interface HTMLBthContaUsuarioElementEventMap {
        "logout": LogoutEvent;
    }
    /**
     * Este componente exibe informações relacionadas ao usuário/conta logada
     * Este componente foi elaborado para comportar o slot "menu_ferramentas"
     */
    interface HTMLBthContaUsuarioElement extends Components.BthContaUsuario, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthContaUsuarioElementEventMap>(type: K, listener: (this: HTMLBthContaUsuarioElement, ev: BthContaUsuarioCustomEvent<HTMLBthContaUsuarioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthContaUsuarioElementEventMap>(type: K, listener: (this: HTMLBthContaUsuarioElement, ev: BthContaUsuarioCustomEvent<HTMLBthContaUsuarioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthContaUsuarioElement: {
        prototype: HTMLBthContaUsuarioElement;
        new (): HTMLBthContaUsuarioElement;
    };
    interface HTMLBthEmptyStateElement extends Components.BthEmptyState, HTMLStencilElement {
    }
    var HTMLBthEmptyStateElement: {
        prototype: HTMLBthEmptyStateElement;
        new (): HTMLBthEmptyStateElement;
    };
    interface HTMLBthIconeElement extends Components.BthIcone, HTMLStencilElement {
    }
    var HTMLBthIconeElement: {
        prototype: HTMLBthIconeElement;
        new (): HTMLBthIconeElement;
    };
    /**
     * Loader padrão com efeitos de animações
     */
    interface HTMLBthLoaderElement extends Components.BthLoader, HTMLStencilElement {
    }
    var HTMLBthLoaderElement: {
        prototype: HTMLBthLoaderElement;
        new (): HTMLBthLoaderElement;
    };
    /**
     * Este componente exibe o logo da Betha e o nome do produto
     * Este componente foi elaborado para comportar o slot de "menu_marca_produto"
     */
    interface HTMLBthMarcaProdutoElement extends Components.BthMarcaProduto, HTMLStencilElement {
    }
    var HTMLBthMarcaProdutoElement: {
        prototype: HTMLBthMarcaProdutoElement;
        new (): HTMLBthMarcaProdutoElement;
    };
    /**
     * Facilita a criação de Ferramentas para o menu. Abstrai comportamentos responsivos e controle do painel lateral.
     */
    interface HTMLBthMenuFerramentaElement extends Components.BthMenuFerramenta, HTMLStencilElement {
    }
    var HTMLBthMenuFerramentaElement: {
        prototype: HTMLBthMenuFerramentaElement;
        new (): HTMLBthMenuFerramentaElement;
    };
    /**
     * Abstrai a estilização de um ícone para menu-ferramenta.
     * Também implementa a possibilidade de exibição de um `badge` ao lado do ícone, através da propriedade `contador`.
     */
    interface HTMLBthMenuFerramentaIconeElement extends Components.BthMenuFerramentaIcone, HTMLStencilElement {
    }
    var HTMLBthMenuFerramentaIconeElement: {
        prototype: HTMLBthMenuFerramentaIconeElement;
        new (): HTMLBthMenuFerramentaIconeElement;
    };
    interface HTMLBthMenuHorizontalItemElementEventMap {
        "menuHorizontalSelecionado": MenuHorizontalSelecionadoEvent;
    }
    /**
     * Item que representa uma opção do menu para navegação horizontal
     */
    interface HTMLBthMenuHorizontalItemElement extends Components.BthMenuHorizontalItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthMenuHorizontalItemElementEventMap>(type: K, listener: (this: HTMLBthMenuHorizontalItemElement, ev: BthMenuHorizontalItemCustomEvent<HTMLBthMenuHorizontalItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthMenuHorizontalItemElementEventMap>(type: K, listener: (this: HTMLBthMenuHorizontalItemElement, ev: BthMenuHorizontalItemCustomEvent<HTMLBthMenuHorizontalItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthMenuHorizontalItemElement: {
        prototype: HTMLBthMenuHorizontalItemElement;
        new (): HTMLBthMenuHorizontalItemElement;
    };
    interface HTMLBthMenuPainelLateralElementEventMap {
        "painelLateralShow": PainelLateralShowEvent;
    }
    /**
     * Possibilita incluir conteúdo dinâmico em um painel lateral que sobrepõe o conteúdo da tela pela direita
     */
    interface HTMLBthMenuPainelLateralElement extends Components.BthMenuPainelLateral, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthMenuPainelLateralElementEventMap>(type: K, listener: (this: HTMLBthMenuPainelLateralElement, ev: BthMenuPainelLateralCustomEvent<HTMLBthMenuPainelLateralElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthMenuPainelLateralElementEventMap>(type: K, listener: (this: HTMLBthMenuPainelLateralElement, ev: BthMenuPainelLateralCustomEvent<HTMLBthMenuPainelLateralElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthMenuPainelLateralElement: {
        prototype: HTMLBthMenuPainelLateralElement;
        new (): HTMLBthMenuPainelLateralElement;
    };
    interface HTMLBthMenuVerticalItemElementEventMap {
        "menuVerticalSelecionado": MenuVerticalSelecionadoEvent;
    }
    /**
     * Item que representa uma opção do menu para navegação vertical
     */
    interface HTMLBthMenuVerticalItemElement extends Components.BthMenuVerticalItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthMenuVerticalItemElementEventMap>(type: K, listener: (this: HTMLBthMenuVerticalItemElement, ev: BthMenuVerticalItemCustomEvent<HTMLBthMenuVerticalItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthMenuVerticalItemElementEventMap>(type: K, listener: (this: HTMLBthMenuVerticalItemElement, ev: BthMenuVerticalItemCustomEvent<HTMLBthMenuVerticalItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthMenuVerticalItemElement: {
        prototype: HTMLBthMenuVerticalItemElement;
        new (): HTMLBthMenuVerticalItemElement;
    };
    interface HTMLBthNavbarPillGroupElement extends Components.BthNavbarPillGroup, HTMLStencilElement {
    }
    var HTMLBthNavbarPillGroupElement: {
        prototype: HTMLBthNavbarPillGroupElement;
        new (): HTMLBthNavbarPillGroupElement;
    };
    interface HTMLBthNavbarPillItemElementEventMap {
        "navbarPillItemClicked": any;
    }
    interface HTMLBthNavbarPillItemElement extends Components.BthNavbarPillItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthNavbarPillItemElementEventMap>(type: K, listener: (this: HTMLBthNavbarPillItemElement, ev: BthNavbarPillItemCustomEvent<HTMLBthNavbarPillItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthNavbarPillItemElementEventMap>(type: K, listener: (this: HTMLBthNavbarPillItemElement, ev: BthNavbarPillItemCustomEvent<HTMLBthNavbarPillItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthNavbarPillItemElement: {
        prototype: HTMLBthNavbarPillItemElement;
        new (): HTMLBthNavbarPillItemElement;
    };
    interface HTMLBthNotificacaoItemElementEventMap {
        "notificacaoLida": any;
        "notificacaoNaoLida": any;
    }
    interface HTMLBthNotificacaoItemElement extends Components.BthNotificacaoItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthNotificacaoItemElementEventMap>(type: K, listener: (this: HTMLBthNotificacaoItemElement, ev: BthNotificacaoItemCustomEvent<HTMLBthNotificacaoItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthNotificacaoItemElementEventMap>(type: K, listener: (this: HTMLBthNotificacaoItemElement, ev: BthNotificacaoItemCustomEvent<HTMLBthNotificacaoItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthNotificacaoItemElement: {
        prototype: HTMLBthNotificacaoItemElement;
        new (): HTMLBthNotificacaoItemElement;
    };
    interface HTMLBthNotificacoesElementEventMap {
        "conteudoSinalizado": ConteudoSinalizadoEvent;
        "novaNotificacao": NotificacaoEvent;
        "novaNotificacaoComLink": NotificacaoComLinkEvent;
    }
    interface HTMLBthNotificacoesElement extends Components.BthNotificacoes, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthNotificacoesElementEventMap>(type: K, listener: (this: HTMLBthNotificacoesElement, ev: BthNotificacoesCustomEvent<HTMLBthNotificacoesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthNotificacoesElementEventMap>(type: K, listener: (this: HTMLBthNotificacoesElement, ev: BthNotificacoesCustomEvent<HTMLBthNotificacoesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthNotificacoesElement: {
        prototype: HTMLBthNotificacoesElement;
        new (): HTMLBthNotificacoesElement;
    };
    interface HTMLBthNovidadeItemElementEventMap {
        "novidadeLida": NovidadeLeituraEvent;
        "novidadeNaoLida": NovidadeLeituraEvent;
    }
    interface HTMLBthNovidadeItemElement extends Components.BthNovidadeItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthNovidadeItemElementEventMap>(type: K, listener: (this: HTMLBthNovidadeItemElement, ev: BthNovidadeItemCustomEvent<HTMLBthNovidadeItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthNovidadeItemElementEventMap>(type: K, listener: (this: HTMLBthNovidadeItemElement, ev: BthNovidadeItemCustomEvent<HTMLBthNovidadeItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthNovidadeItemElement: {
        prototype: HTMLBthNovidadeItemElement;
        new (): HTMLBthNovidadeItemElement;
    };
    interface HTMLBthNovidadesElementEventMap {
        "conteudoSinalizado": ConteudoSinalizadoEvent;
    }
    interface HTMLBthNovidadesElement extends Components.BthNovidades, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthNovidadesElementEventMap>(type: K, listener: (this: HTMLBthNovidadesElement, ev: BthNovidadesCustomEvent<HTMLBthNovidadesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthNovidadesElementEventMap>(type: K, listener: (this: HTMLBthNovidadesElement, ev: BthNovidadesCustomEvent<HTMLBthNovidadesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthNovidadesElement: {
        prototype: HTMLBthNovidadesElement;
        new (): HTMLBthNovidadesElement;
    };
    interface HTMLBthPesquisaElement extends Components.BthPesquisa, HTMLStencilElement {
    }
    var HTMLBthPesquisaElement: {
        prototype: HTMLBthPesquisaElement;
        new (): HTMLBthPesquisaElement;
    };
    /**
     * Este componente permite compor uma lista de seleção de contexto.
     */
    interface HTMLBthSelecaoContextoElement extends Components.BthSelecaoContexto, HTMLStencilElement {
    }
    var HTMLBthSelecaoContextoElement: {
        prototype: HTMLBthSelecaoContextoElement;
        new (): HTMLBthSelecaoContextoElement;
    };
    /**
     * Componente do menu Suporte com Blip Chat
     * @see https://gitlab.services.betha.cloud/ped/tecnologia/nlp/blip-webchat-loader
     * @see https://gitlab.services.betha.cloud/ped/suite/atendimento/components/suite-atendimento
     */
    interface HTMLBthSuporteElement extends Components.BthSuporte, HTMLStencilElement {
    }
    var HTMLBthSuporteElement: {
        prototype: HTMLBthSuporteElement;
        new (): HTMLBthSuporteElement;
    };
    interface HTMLBthUtilitariosElementEventMap {
        "opcaoUtilitarioSelecionada": OpcaoUtilitarioSelecionadaEvent;
    }
    interface HTMLBthUtilitariosElement extends Components.BthUtilitarios, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBthUtilitariosElementEventMap>(type: K, listener: (this: HTMLBthUtilitariosElement, ev: BthUtilitariosCustomEvent<HTMLBthUtilitariosElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBthUtilitariosElementEventMap>(type: K, listener: (this: HTMLBthUtilitariosElement, ev: BthUtilitariosCustomEvent<HTMLBthUtilitariosElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBthUtilitariosElement: {
        prototype: HTMLBthUtilitariosElement;
        new (): HTMLBthUtilitariosElement;
    };
    interface HTMLElementTagNameMap {
        "bth-ajuda": HTMLBthAjudaElement;
        "bth-app": HTMLBthAppElement;
        "bth-avatar": HTMLBthAvatarElement;
        "bth-conta-usuario": HTMLBthContaUsuarioElement;
        "bth-empty-state": HTMLBthEmptyStateElement;
        "bth-icone": HTMLBthIconeElement;
        "bth-loader": HTMLBthLoaderElement;
        "bth-marca-produto": HTMLBthMarcaProdutoElement;
        "bth-menu-ferramenta": HTMLBthMenuFerramentaElement;
        "bth-menu-ferramenta-icone": HTMLBthMenuFerramentaIconeElement;
        "bth-menu-horizontal-item": HTMLBthMenuHorizontalItemElement;
        "bth-menu-painel-lateral": HTMLBthMenuPainelLateralElement;
        "bth-menu-vertical-item": HTMLBthMenuVerticalItemElement;
        "bth-navbar-pill-group": HTMLBthNavbarPillGroupElement;
        "bth-navbar-pill-item": HTMLBthNavbarPillItemElement;
        "bth-notificacao-item": HTMLBthNotificacaoItemElement;
        "bth-notificacoes": HTMLBthNotificacoesElement;
        "bth-novidade-item": HTMLBthNovidadeItemElement;
        "bth-novidades": HTMLBthNovidadesElement;
        "bth-pesquisa": HTMLBthPesquisaElement;
        "bth-selecao-contexto": HTMLBthSelecaoContextoElement;
        "bth-suporte": HTMLBthSuporteElement;
        "bth-utilitarios": HTMLBthUtilitariosElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface BthAjuda {
        /**
          * URL para a home da central de ajuda. Por padrão irá obter do env.js
         */
        "centralAjudaHome"?: string;
    }
    /**
     * Permite configurar opções de navegação nos modelos de menu horizontal e vertical.
     * Possui áreas pré-definidas que permite compor as aplicações.
     */
    interface BthApp {
        /**
          * Permite definir um banner que é exibido acima do menu
         */
        "banner"?: Banner;
        /**
          * Permite customizar a cor de fundo da barra do menu. Por padrão segue a cor da linha dos produtos.
         */
        "menuBgColor"?: string;
        /**
          * Define se as opções do menu serão exibidas no formato "vertical", caso contrário serão exibidas no formato "horizontal"
          * @default false
         */
        "menuVertical"?: boolean;
        /**
          * É emitido quando o componente de menu possuir alterações na propriedade de banner
         */
        "onBannerAlterado"?: (event: BthAppCustomEvent<MenuBannerAlteradoEvent>) => void;
        /**
          * É emitido quando o botão do banner é clicado
         */
        "onBotaoBannerAcionado"?: (event: BthAppCustomEvent<void>) => void;
        /**
          * É emitido quando alguma opção do menu for selecionada
         */
        "onOpcaoMenuSelecionada"?: (event: BthAppCustomEvent<OpcaoMenuSelecionadaEvent>) => void;
        /**
          * Opções de navegação do menu
          * @default []
         */
        "opcoes"?: Array<OpcaoMenu>;
        /**
          * Opções de navegação a serem exibidas no header, ao lado da marca. Funciona de forma independente da navegação principal, e somente se o menu for vertical.
          * @default []
         */
        "opcoesHeader"?: Array<OpcaoMenu>;
    }
    /**
     * Este componente exibe um avatar
     */
    interface BthAvatar {
        /**
          * Define se o avatar possui borda
          * @default false
         */
        "borda"?: boolean;
        /**
          * Define a cor da borda
          * @default 'white'
         */
        "bordaCor"?: string;
        /**
          * Define o raio da borda do avatar. Caso informado, sobrescreve o atributo utilitario 'quadrado'.
          * @default '50%'
         */
        "bordaRaio"?: string;
        /**
          * Define o tamanho da borda
          * @default '1px'
         */
        "bordaTamanho"?: string;
        /**
          * Permite definir a dimensão (largura, altura) em px para o avatar
         */
        "dimensao"?: number;
        /**
          * Define um avatar de ícone conforme biblioteca `"Material Design Icons"`
         */
        "icone"?: string;
        /**
          * Define avatar do tipo iniciais, aceitando até 3 iniciais ou computando as iniciais automaticamente conforme palavras passadas
         */
        "iniciais"?: string;
        /**
          * É emitido quando houver erro ao carregar a imagem
         */
        "onImageLoadError"?: (event: BthAvatarCustomEvent<any>) => void;
        /**
          * Define se o avatar terá suas bordas no formato quadrado.  Por padrão é redondo
          * @default false
         */
        "quadrado"?: boolean;
        /**
          * Define a fonte de um avatar de imagem. Aceita imagem e svg.
         */
        "src"?: string;
        /**
          * Define um sub-ícone conforme biblioteca `"Material Design Icons"`
         */
        "subIcone"?: string;
        /**
          * Define o "title" do subícone
          * @default ''
         */
        "subIconeTitle"?: string;
        /**
          * Define o tamanho conforme dimensões pre-definidas para o avatar.  Opções disponíveis: menor (24x24), pequeno (28x28), medio (48x48) e grande (94x94)
          * @default 'medio'
         */
        "tamanho"?: Tamanho;
    }
    /**
     * Este componente exibe informações relacionadas ao usuário/conta logada
     * Este componente foi elaborado para comportar o slot "menu_ferramentas"
     */
    interface BthContaUsuario {
        /**
          * URL para home da Central de Usuários. Por padrão irá obter do env.js.
         */
        "centralUsuarioHome"?: string;
        /**
          * URL para foto de avatar do usuário
         */
        "fotoUrl"?: string;
        /**
          * Nome do usuário
         */
        "nome"?: string;
        /**
          * É emitido ao clicar em Sair ("logout")
         */
        "onLogout"?: (event: BthContaUsuarioCustomEvent<LogoutEvent>) => void;
        /**
          * Usuário ("username" ou "email")
         */
        "usuario"?: string;
    }
    interface BthEmptyState {
        /**
          * Define se o empty state é para conexão offline
          * @default false
         */
        "offline"?: boolean;
        /**
          * Define se o empty state é para conexão online
          * @default false
         */
        "online"?: boolean;
        /**
          * Define se o empty state é para página não encontrada
          * @default false
         */
        "paginaNaoEncontrada"?: boolean;
        /**
          * Define se o empty state é de tamanho pequeno
          * @default false
         */
        "pequeno"?: boolean;
        /**
          * Define se o empty state é para registros
          * @default false
         */
        "registros"?: boolean;
        /**
          * Define se o empty state é para registros com pesquisa
          * @default false
         */
        "registrosPesquisa"?: boolean;
        /**
          * Define se o empty state está visível
          * @default false
         */
        "show"?: boolean;
    }
    interface BthIcone {
        /**
          * Especifica o label a ser utilizado para acessibilidade. Por padrão irá assumir o nome do ícone.
         */
        "ariaLabel"?: string | null;
        /**
          * Cor de preenchimento, no mesmo formato do `"color"` em CSS. Por padrão irá herdar do contexto inserido.
          * @default 'inherit'
         */
        "cor"?: string;
        /**
          * Identificador do ícone conforme biblioteca `"Material Design Icons"`
         */
        "icone": string;
        /**
          * Tamanho em pixels, no mesmo formato do `"font-size"` em CSS. Por padrão irá herdar do contexto inserido.
          * @default 'inherit'
         */
        "tamanho"?: string;
    }
    /**
     * Loader padrão com efeitos de animações
     */
    interface BthLoader {
        /**
          * Define se o loader é inline
          * @default false
         */
        "inline"?: boolean;
    }
    /**
     * Este componente exibe o logo da Betha e o nome do produto
     * Este componente foi elaborado para comportar o slot de "menu_marca_produto"
     */
    interface BthMarcaProduto {
        /**
          * Define a área de produtos.
         */
        "area"?: string;
        /**
          * Configuração de autorização. É necessária para o componente poder se autentizar com os serviços.
         */
        "authorization"?: AuthorizationConfig;
        /**
          * Define se o componente exibirá os produtos, condicionando a busca. Caso informado `false` não irá buscar por produtos.
          * @default false
         */
        "exibirProdutos"?: boolean;
        /**
          * Nome do produto
         */
        "produto": string;
        /**
          * URL para a home da betha store. Por padrão irá obter do env.js
         */
        "storeHome"?: string;
        /**
          * URL para home da suite de usuários. Por padrão irá obter do env.js
         */
        "suiteHome"?: string;
        /**
          * URL para a API de user accounts. Por padrão irá obter do env.js
         */
        "userAccountsApi"?: string;
    }
    /**
     * Facilita a criação de Ferramentas para o menu. Abstrai comportamentos responsivos e controle do painel lateral.
     */
    interface BthMenuFerramenta {
        /**
          * Descrição
          * @default ''
         */
        "descricao"?: string;
        /**
          * Título do Painel Lateral
         */
        "tituloPainelLateral"?: string;
    }
    /**
     * Abstrai a estilização de um ícone para menu-ferramenta.
     * Também implementa a possibilidade de exibição de um `badge` ao lado do ícone, através da propriedade `contador`.
     */
    interface BthMenuFerramentaIcone {
        /**
          * Valor que será exibido em uma "badge" próximo ao ícone
          * @default 0
         */
        "contador"?: number;
        /**
          * Ícone conforme biblioteca `"Material Design Icons"`
          * @default 'cloud'
         */
        "icone"?: string;
        /**
          * Define se a estilização é "mobile". Por padrão é "desktop".
          * @default false
         */
        "mobile"?: boolean;
        /**
          * Badge de Status
         */
        "status"?: 'online' | 'offline' | undefined;
    }
    /**
     * Item que representa uma opção do menu para navegação horizontal
     */
    interface BthMenuHorizontalItem {
        /**
          * Está ativo?
         */
        "ativo"?: boolean;
        /**
          * Contador  Exibe o valor inforamdo em um badge próximo ao menu
         */
        "contador"?: number;
        /**
          * Descrição
         */
        "descricao"?: string;
        /**
          * Identificador
         */
        "identificador"?: IdentificadorOpcaoMenu;
        /**
          * É emitido quando o menu é selecionado
         */
        "onMenuHorizontalSelecionado"?: (event: BthMenuHorizontalItemCustomEvent<MenuHorizontalSelecionadoEvent>) => void;
        /**
          * Possui permissão?
          * @default true
         */
        "possuiPermissao"?: boolean;
    }
    /**
     * Possibilita incluir conteúdo dinâmico em um painel lateral que sobrepõe o conteúdo da tela pela direita
     */
    interface BthMenuPainelLateral {
        /**
          * É toda vez em que o estado de exibição ("show") for alterado
         */
        "onPainelLateralShow"?: (event: BthMenuPainelLateralCustomEvent<PainelLateralShowEvent>) => void;
        /**
          * Estado de visibilidade
          * @default false
         */
        "show"?: boolean;
        /**
          * Título que será exibido no cabeçalho
         */
        "titulo"?: string;
    }
    /**
     * Item que representa uma opção do menu para navegação vertical
     */
    interface BthMenuVerticalItem {
        /**
          * Está ativo?
         */
        "ativo"?: boolean;
        /**
          * Valor que será exibido em uma "badge" próximo ao menu
         */
        "contador"?: number;
        /**
          * Descrição
         */
        "descricao"?: string;
        /**
          * Ícone conforme biblioteca `"Material Design Icons"`
         */
        "icone"?: string;
        /**
          * Identificador
         */
        "identificador"?: IdentificadorOpcaoMenu;
        /**
          * Identificador do menu agrupador "pai"
         */
        "identificadorPai"?: IdentificadorOpcaoMenu;
        /**
          * O menu principal está recolhido?  Este parâmetro influência no formato como alguns elementos são exibidos, ex: badge do contador.
         */
        "menuLateralRecolhido"?: boolean;
        /**
          * É emitido quando o menu é selecionado
         */
        "onMenuVerticalSelecionado"?: (event: BthMenuVerticalItemCustomEvent<MenuVerticalSelecionadoEvent>) => void;
        /**
          * Indica se deve aparecer um badge no ícone.
         */
        "possuiBadgeIcone"?: boolean;
        /**
          * Possui permissão?
          * @default true
         */
        "possuiPermissao"?: boolean;
        /**
          * Está recolhido?
         */
        "recolhido"?: boolean;
        /**
          * É um submenu?
         */
        "submenu"?: boolean;
        /**
          * Possui submenus?
         */
        "submenus"?: Array<OpcaoMenu>;
    }
    interface BthNavbarPillGroup {
        /**
          * Descrição
         */
        "descricao"?: string;
    }
    interface BthNavbarPillItem {
        /**
          * Está ativo?
          * @default false
         */
        "ativo"?: boolean;
        /**
          * Descrição
         */
        "descricao"?: string;
        /**
          * Ícone conforme biblioteca `"Material Design Icons"`
          * @default 'cloud-question'
         */
        "icone"?: string;
        /**
          * Identificador. É enviado no evento de click.
         */
        "identificador"?: any;
        /**
          * É emitido ao clicar no filtro
         */
        "onNavbarPillItemClicked"?: (event: BthNavbarPillItemCustomEvent<any>) => void;
        /**
          * Exibir totalizador?
          * @default true
         */
        "showTotalizador"?: boolean;
        /**
          * Totalizador
          * @default 0
         */
        "totalizador"?: number;
    }
    interface BthNotificacaoItem {
        /**
          * Link acompanhar
         */
        "acompanharLink"?: NotificacaoLink;
        /**
          * Link cancelamento
         */
        "cancelamentoLink"?: NotificacaoLink;
        /**
          * Data e hora
         */
        "dataHora"?: number | string;
        /**
          * Ícone
         */
        "icone"?: string;
        /**
          * Identificador
         */
        "identificador"?: string;
        /**
          * É emitido quando uma notificação é marcada como lida
         */
        "onNotificacaoLida"?: (event: BthNotificacaoItemCustomEvent<any>) => void;
        /**
          * É emitido quando uma notificação é marcada como não lida
         */
        "onNotificacaoNaoLida"?: (event: BthNotificacaoItemCustomEvent<any>) => void;
        /**
          * Origem
         */
        "origem"?: string;
        /**
          * Percentual do progresso
         */
        "percentualProgresso"?: number;
        /**
          * Possui progresso?
         */
        "possuiProgresso"?: boolean;
        /**
          * Prioridade
         */
        "prioridade"?: number;
        /**
          * Link resultado
         */
        "resultadoLink"?: NotificacaoLink;
        /**
          * Status
         */
        "status"?: string;
        /**
          * Texto
         */
        "texto"?: string;
        /**
          * Tipo de notificação
         */
        "tipo"?: TipoNotificacao;
    }
    interface BthNotificacoes {
        /**
          * Configuração de autorização. É necessária para o componente poder realizar autentizar com os serviços.
         */
        "authorization"?: AuthorizationConfig;
        /**
          * URL para a api de notificações. Por padrão irá obter do env.js
         */
        "notificacoesApi"?: string;
        /**
          * URL para o channel websocket de notificações. Por padrão irá obter do env.js
         */
        "notificacoesWs"?: string;
        /**
          * É emitido quando houver notificações lidas ou não lidas a ser sinalizadas ao menu
         */
        "onConteudoSinalizado"?: (event: BthNotificacoesCustomEvent<ConteudoSinalizadoEvent>) => void;
        /**
          * É emitido quando alguma notificação for recebida
         */
        "onNovaNotificacao"?: (event: BthNotificacoesCustomEvent<NotificacaoEvent>) => void;
        /**
          * É emitido quando alguma notificação do tipo mensagem for recebida
         */
        "onNovaNotificacaoComLink"?: (event: BthNotificacoesCustomEvent<NotificacaoComLinkEvent>) => void;
    }
    interface BthNovidadeItem {
        /**
          * Data e hora
         */
        "dataHora"?: string;
        /**
          * Identificador
         */
        "identificador"?: string;
        /**
          * Define se já está lida
          * @default false
         */
        "isLida"?: boolean;
        /**
          * Mensagem
         */
        "mensagem"?: string;
        /**
          * É emitido quando uma novidade é marcada como lida
         */
        "onNovidadeLida"?: (event: BthNovidadeItemCustomEvent<NovidadeLeituraEvent>) => void;
        /**
          * É emitido quando uma novidade é marcada como não lida
         */
        "onNovidadeNaoLida"?: (event: BthNovidadeItemCustomEvent<NovidadeLeituraEvent>) => void;
        /**
          * Título
         */
        "titulo"?: string;
        /**
          * URL para obter mais informações
         */
        "url"?: string;
    }
    interface BthNovidades {
        /**
          * Configuração de autorização. É necessária para o componente poder realizar autentizar com os serviços.
         */
        "authorization"?: AuthorizationConfig;
        /**
          * URL para a api de novidades. Por padrão irá obter do env.js.
         */
        "novidadesApi"?: string;
        /**
          * É emitido quando houver novidades lidas ou não lidas a ser sinalizadas ao menu
         */
        "onConteudoSinalizado"?: (event: BthNovidadesCustomEvent<ConteudoSinalizadoEvent>) => void;
    }
    interface BthPesquisa {
        /**
          * Configuração de autorização. É necessária para o componente poder autenticar com os serviços.
         */
        "authorization"?: AuthorizationConfig;
        /**
          * URL para a api de licenças. Por padrão irá obter do env.js.
         */
        "licencasApi"?: string;
        /**
          * URL para a api de pesquisas. Por padrão irá obter do env.js.
         */
        "pesquisaApi"?: string;
    }
    /**
     * Este componente permite compor uma lista de seleção de contexto.
     */
    interface BthSelecaoContexto {
        /**
          * Método para buscar os itens de seleção
         */
        "buscar"?: () => Promise<ItemSelecaoContexto[]>;
        /**
          * Placeholder para o input de pesquisa
         */
        "placeholderPesquisa"?: string;
        /**
          * Método executado ao selecionar algum item da lista
         */
        "selecionar"?: (item: ItemSelecaoContexto) => Promise<any> | void;
    }
    /**
     * Componente do menu Suporte com Blip Chat
     * @see https://gitlab.services.betha.cloud/ped/tecnologia/nlp/blip-webchat-loader
     * @see https://gitlab.services.betha.cloud/ped/suite/atendimento/components/suite-atendimento
     */
    interface BthSuporte {
        /**
          * Habilita ou desabilita o botão de abrir um chamado no atendimento
          * @default false
         */
        "atendimento"?: boolean;
        /**
          * Configuração de autorização. É necessária para o componente poder autenticar com os serviços.
         */
        "authorization"?: AuthorizationConfig;
        /**
          * Habilita ou desabilita o Blip Chat
          * @default false
         */
        "blipChat"?: boolean;
        /**
          * Usar estilos que este componente fornece
          * @default false
         */
        "blipChatCustomStyle"?: boolean;
        /**
          * Cor do botão flutuante do Blip Chat
         */
        "blipChatFabButtonColor"?: string;
        /**
          * Usuário de sessão do Blip Chat
         */
        "blipChatUserInfo"?: BlipChatUserInfo;
        /**
          * URL para a home da central de ajuda. Por padrão irá obter do env.js
         */
        "centralAjudaHome"?: string;
        /**
          * Indica se a aplicação já possui botão flutuante
          * @default false
         */
        "fabButton"?: boolean;
        /**
          * URL para a api de licenças. Por padrão irá obter do env.js.
         */
        "licencasApi"?: string;
    }
    interface BthUtilitarios {
        /**
          * É emitido quando algum utilitário for selecionado
         */
        "onOpcaoUtilitarioSelecionada"?: (event: BthUtilitariosCustomEvent<OpcaoUtilitarioSelecionadaEvent>) => void;
        /**
          * Utilitarios
         */
        "utilitarios"?: Array<Utilitario>;
    }

    interface BthAjudaAttributes {
        "centralAjudaHome": string;
    }
    interface BthAppAttributes {
        "menuVertical": boolean;
        "menuBgColor": string;
    }
    interface BthAvatarAttributes {
        "icone": string;
        "subIcone": string;
        "subIconeTitle": string;
        "src": string;
        "iniciais": string;
        "tamanho": Tamanho;
        "dimensao": number;
        "quadrado": boolean;
        "borda": boolean;
        "bordaTamanho": string;
        "bordaRaio": string;
        "bordaCor": string;
    }
    interface BthContaUsuarioAttributes {
        "centralUsuarioHome": string;
        "fotoUrl": string;
        "nome": string;
        "usuario": string;
    }
    interface BthEmptyStateAttributes {
        "show": boolean;
        "registros": boolean;
        "registrosPesquisa": boolean;
        "online": boolean;
        "offline": boolean;
        "paginaNaoEncontrada": boolean;
        "pequeno": boolean;
    }
    interface BthIconeAttributes {
        "icone": string;
        "tamanho": string;
        "cor": string;
        "ariaLabel": string | null;
    }
    interface BthLoaderAttributes {
        "inline": boolean;
    }
    interface BthMarcaProdutoAttributes {
        "produto": string;
        "area": string;
        "exibirProdutos": boolean;
        "userAccountsApi": string;
        "suiteHome": string;
        "storeHome": string;
    }
    interface BthMenuFerramentaAttributes {
        "descricao": string;
        "tituloPainelLateral": string;
    }
    interface BthMenuFerramentaIconeAttributes {
        "contador": number;
        "icone": string;
        "mobile": boolean;
        "status": 'online' | 'offline' | undefined;
    }
    interface BthMenuHorizontalItemAttributes {
        "ativo": boolean;
        "contador": number;
        "descricao": string;
        "identificador": string;
        "possuiPermissao": boolean;
    }
    interface BthMenuPainelLateralAttributes {
        "show": boolean;
        "titulo": string;
    }
    interface BthMenuVerticalItemAttributes {
        "ativo": boolean;
        "contador": number;
        "possuiBadgeIcone": boolean;
        "descricao": string;
        "icone": string;
        "identificador": string;
        "identificadorPai": string;
        "menuLateralRecolhido": boolean;
        "possuiPermissao": boolean;
        "recolhido": boolean;
        "submenu": boolean;
    }
    interface BthNavbarPillGroupAttributes {
        "descricao": string;
    }
    interface BthNavbarPillItemAttributes {
        "identificador": string;
        "descricao": string;
        "ativo": boolean;
        "icone": string;
        "totalizador": number;
        "showTotalizador": boolean;
    }
    interface BthNotificacaoItemAttributes {
        "identificador": string;
        "tipo": TipoNotificacao;
        "texto": string;
        "dataHora": string;
        "origem": string;
        "icone": string;
        "possuiProgresso": boolean;
        "percentualProgresso": number;
        "status": string;
        "prioridade": number;
    }
    interface BthNotificacoesAttributes {
        "notificacoesApi": string;
        "notificacoesWs": string;
    }
    interface BthNovidadeItemAttributes {
        "identificador": string;
        "titulo": string;
        "mensagem": string;
        "isLida": boolean;
        "url": string;
        "dataHora": string;
    }
    interface BthNovidadesAttributes {
        "novidadesApi": string;
    }
    interface BthPesquisaAttributes {
        "pesquisaApi": string;
        "licencasApi": string;
    }
    interface BthSelecaoContextoAttributes {
        "placeholderPesquisa": string;
    }
    interface BthSuporteAttributes {
        "blipChat": boolean;
        "blipChatCustomStyle": boolean;
        "blipChatFabButtonColor": string;
        "fabButton": boolean;
        "centralAjudaHome": string;
        "atendimento": boolean;
        "licencasApi": string;
    }

    interface IntrinsicElements {
        "bth-ajuda": Omit<BthAjuda, keyof BthAjudaAttributes> & { [K in keyof BthAjuda & keyof BthAjudaAttributes]?: BthAjuda[K] } & { [K in keyof BthAjuda & keyof BthAjudaAttributes as `attr:${K}`]?: BthAjudaAttributes[K] } & { [K in keyof BthAjuda & keyof BthAjudaAttributes as `prop:${K}`]?: BthAjuda[K] };
        "bth-app": Omit<BthApp, keyof BthAppAttributes> & { [K in keyof BthApp & keyof BthAppAttributes]?: BthApp[K] } & { [K in keyof BthApp & keyof BthAppAttributes as `attr:${K}`]?: BthAppAttributes[K] } & { [K in keyof BthApp & keyof BthAppAttributes as `prop:${K}`]?: BthApp[K] };
        "bth-avatar": Omit<BthAvatar, keyof BthAvatarAttributes> & { [K in keyof BthAvatar & keyof BthAvatarAttributes]?: BthAvatar[K] } & { [K in keyof BthAvatar & keyof BthAvatarAttributes as `attr:${K}`]?: BthAvatarAttributes[K] } & { [K in keyof BthAvatar & keyof BthAvatarAttributes as `prop:${K}`]?: BthAvatar[K] };
        "bth-conta-usuario": Omit<BthContaUsuario, keyof BthContaUsuarioAttributes> & { [K in keyof BthContaUsuario & keyof BthContaUsuarioAttributes]?: BthContaUsuario[K] } & { [K in keyof BthContaUsuario & keyof BthContaUsuarioAttributes as `attr:${K}`]?: BthContaUsuarioAttributes[K] } & { [K in keyof BthContaUsuario & keyof BthContaUsuarioAttributes as `prop:${K}`]?: BthContaUsuario[K] };
        "bth-empty-state": Omit<BthEmptyState, keyof BthEmptyStateAttributes> & { [K in keyof BthEmptyState & keyof BthEmptyStateAttributes]?: BthEmptyState[K] } & { [K in keyof BthEmptyState & keyof BthEmptyStateAttributes as `attr:${K}`]?: BthEmptyStateAttributes[K] } & { [K in keyof BthEmptyState & keyof BthEmptyStateAttributes as `prop:${K}`]?: BthEmptyState[K] };
        "bth-icone": Omit<BthIcone, keyof BthIconeAttributes> & { [K in keyof BthIcone & keyof BthIconeAttributes]?: BthIcone[K] } & { [K in keyof BthIcone & keyof BthIconeAttributes as `attr:${K}`]?: BthIconeAttributes[K] } & { [K in keyof BthIcone & keyof BthIconeAttributes as `prop:${K}`]?: BthIcone[K] } & OneOf<"icone", BthIcone["icone"], BthIconeAttributes["icone"]>;
        "bth-loader": Omit<BthLoader, keyof BthLoaderAttributes> & { [K in keyof BthLoader & keyof BthLoaderAttributes]?: BthLoader[K] } & { [K in keyof BthLoader & keyof BthLoaderAttributes as `attr:${K}`]?: BthLoaderAttributes[K] } & { [K in keyof BthLoader & keyof BthLoaderAttributes as `prop:${K}`]?: BthLoader[K] };
        "bth-marca-produto": Omit<BthMarcaProduto, keyof BthMarcaProdutoAttributes> & { [K in keyof BthMarcaProduto & keyof BthMarcaProdutoAttributes]?: BthMarcaProduto[K] } & { [K in keyof BthMarcaProduto & keyof BthMarcaProdutoAttributes as `attr:${K}`]?: BthMarcaProdutoAttributes[K] } & { [K in keyof BthMarcaProduto & keyof BthMarcaProdutoAttributes as `prop:${K}`]?: BthMarcaProduto[K] } & OneOf<"produto", BthMarcaProduto["produto"], BthMarcaProdutoAttributes["produto"]>;
        "bth-menu-ferramenta": Omit<BthMenuFerramenta, keyof BthMenuFerramentaAttributes> & { [K in keyof BthMenuFerramenta & keyof BthMenuFerramentaAttributes]?: BthMenuFerramenta[K] } & { [K in keyof BthMenuFerramenta & keyof BthMenuFerramentaAttributes as `attr:${K}`]?: BthMenuFerramentaAttributes[K] } & { [K in keyof BthMenuFerramenta & keyof BthMenuFerramentaAttributes as `prop:${K}`]?: BthMenuFerramenta[K] };
        "bth-menu-ferramenta-icone": Omit<BthMenuFerramentaIcone, keyof BthMenuFerramentaIconeAttributes> & { [K in keyof BthMenuFerramentaIcone & keyof BthMenuFerramentaIconeAttributes]?: BthMenuFerramentaIcone[K] } & { [K in keyof BthMenuFerramentaIcone & keyof BthMenuFerramentaIconeAttributes as `attr:${K}`]?: BthMenuFerramentaIconeAttributes[K] } & { [K in keyof BthMenuFerramentaIcone & keyof BthMenuFerramentaIconeAttributes as `prop:${K}`]?: BthMenuFerramentaIcone[K] };
        "bth-menu-horizontal-item": Omit<BthMenuHorizontalItem, keyof BthMenuHorizontalItemAttributes> & { [K in keyof BthMenuHorizontalItem & keyof BthMenuHorizontalItemAttributes]?: BthMenuHorizontalItem[K] } & { [K in keyof BthMenuHorizontalItem & keyof BthMenuHorizontalItemAttributes as `attr:${K}`]?: BthMenuHorizontalItemAttributes[K] } & { [K in keyof BthMenuHorizontalItem & keyof BthMenuHorizontalItemAttributes as `prop:${K}`]?: BthMenuHorizontalItem[K] };
        "bth-menu-painel-lateral": Omit<BthMenuPainelLateral, keyof BthMenuPainelLateralAttributes> & { [K in keyof BthMenuPainelLateral & keyof BthMenuPainelLateralAttributes]?: BthMenuPainelLateral[K] } & { [K in keyof BthMenuPainelLateral & keyof BthMenuPainelLateralAttributes as `attr:${K}`]?: BthMenuPainelLateralAttributes[K] } & { [K in keyof BthMenuPainelLateral & keyof BthMenuPainelLateralAttributes as `prop:${K}`]?: BthMenuPainelLateral[K] };
        "bth-menu-vertical-item": Omit<BthMenuVerticalItem, keyof BthMenuVerticalItemAttributes> & { [K in keyof BthMenuVerticalItem & keyof BthMenuVerticalItemAttributes]?: BthMenuVerticalItem[K] } & { [K in keyof BthMenuVerticalItem & keyof BthMenuVerticalItemAttributes as `attr:${K}`]?: BthMenuVerticalItemAttributes[K] } & { [K in keyof BthMenuVerticalItem & keyof BthMenuVerticalItemAttributes as `prop:${K}`]?: BthMenuVerticalItem[K] };
        "bth-navbar-pill-group": Omit<BthNavbarPillGroup, keyof BthNavbarPillGroupAttributes> & { [K in keyof BthNavbarPillGroup & keyof BthNavbarPillGroupAttributes]?: BthNavbarPillGroup[K] } & { [K in keyof BthNavbarPillGroup & keyof BthNavbarPillGroupAttributes as `attr:${K}`]?: BthNavbarPillGroupAttributes[K] } & { [K in keyof BthNavbarPillGroup & keyof BthNavbarPillGroupAttributes as `prop:${K}`]?: BthNavbarPillGroup[K] };
        "bth-navbar-pill-item": Omit<BthNavbarPillItem, keyof BthNavbarPillItemAttributes> & { [K in keyof BthNavbarPillItem & keyof BthNavbarPillItemAttributes]?: BthNavbarPillItem[K] } & { [K in keyof BthNavbarPillItem & keyof BthNavbarPillItemAttributes as `attr:${K}`]?: BthNavbarPillItemAttributes[K] } & { [K in keyof BthNavbarPillItem & keyof BthNavbarPillItemAttributes as `prop:${K}`]?: BthNavbarPillItem[K] };
        "bth-notificacao-item": Omit<BthNotificacaoItem, keyof BthNotificacaoItemAttributes> & { [K in keyof BthNotificacaoItem & keyof BthNotificacaoItemAttributes]?: BthNotificacaoItem[K] } & { [K in keyof BthNotificacaoItem & keyof BthNotificacaoItemAttributes as `attr:${K}`]?: BthNotificacaoItemAttributes[K] } & { [K in keyof BthNotificacaoItem & keyof BthNotificacaoItemAttributes as `prop:${K}`]?: BthNotificacaoItem[K] };
        "bth-notificacoes": Omit<BthNotificacoes, keyof BthNotificacoesAttributes> & { [K in keyof BthNotificacoes & keyof BthNotificacoesAttributes]?: BthNotificacoes[K] } & { [K in keyof BthNotificacoes & keyof BthNotificacoesAttributes as `attr:${K}`]?: BthNotificacoesAttributes[K] } & { [K in keyof BthNotificacoes & keyof BthNotificacoesAttributes as `prop:${K}`]?: BthNotificacoes[K] };
        "bth-novidade-item": Omit<BthNovidadeItem, keyof BthNovidadeItemAttributes> & { [K in keyof BthNovidadeItem & keyof BthNovidadeItemAttributes]?: BthNovidadeItem[K] } & { [K in keyof BthNovidadeItem & keyof BthNovidadeItemAttributes as `attr:${K}`]?: BthNovidadeItemAttributes[K] } & { [K in keyof BthNovidadeItem & keyof BthNovidadeItemAttributes as `prop:${K}`]?: BthNovidadeItem[K] };
        "bth-novidades": Omit<BthNovidades, keyof BthNovidadesAttributes> & { [K in keyof BthNovidades & keyof BthNovidadesAttributes]?: BthNovidades[K] } & { [K in keyof BthNovidades & keyof BthNovidadesAttributes as `attr:${K}`]?: BthNovidadesAttributes[K] } & { [K in keyof BthNovidades & keyof BthNovidadesAttributes as `prop:${K}`]?: BthNovidades[K] };
        "bth-pesquisa": Omit<BthPesquisa, keyof BthPesquisaAttributes> & { [K in keyof BthPesquisa & keyof BthPesquisaAttributes]?: BthPesquisa[K] } & { [K in keyof BthPesquisa & keyof BthPesquisaAttributes as `attr:${K}`]?: BthPesquisaAttributes[K] } & { [K in keyof BthPesquisa & keyof BthPesquisaAttributes as `prop:${K}`]?: BthPesquisa[K] };
        "bth-selecao-contexto": Omit<BthSelecaoContexto, keyof BthSelecaoContextoAttributes> & { [K in keyof BthSelecaoContexto & keyof BthSelecaoContextoAttributes]?: BthSelecaoContexto[K] } & { [K in keyof BthSelecaoContexto & keyof BthSelecaoContextoAttributes as `attr:${K}`]?: BthSelecaoContextoAttributes[K] } & { [K in keyof BthSelecaoContexto & keyof BthSelecaoContextoAttributes as `prop:${K}`]?: BthSelecaoContexto[K] };
        "bth-suporte": Omit<BthSuporte, keyof BthSuporteAttributes> & { [K in keyof BthSuporte & keyof BthSuporteAttributes]?: BthSuporte[K] } & { [K in keyof BthSuporte & keyof BthSuporteAttributes as `attr:${K}`]?: BthSuporteAttributes[K] } & { [K in keyof BthSuporte & keyof BthSuporteAttributes as `prop:${K}`]?: BthSuporte[K] };
        "bth-utilitarios": BthUtilitarios;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bth-ajuda": LocalJSX.IntrinsicElements["bth-ajuda"] & JSXBase.HTMLAttributes<HTMLBthAjudaElement>;
            /**
             * Permite configurar opções de navegação nos modelos de menu horizontal e vertical.
             * Possui áreas pré-definidas que permite compor as aplicações.
             */
            "bth-app": LocalJSX.IntrinsicElements["bth-app"] & JSXBase.HTMLAttributes<HTMLBthAppElement>;
            /**
             * Este componente exibe um avatar
             */
            "bth-avatar": LocalJSX.IntrinsicElements["bth-avatar"] & JSXBase.HTMLAttributes<HTMLBthAvatarElement>;
            /**
             * Este componente exibe informações relacionadas ao usuário/conta logada
             * Este componente foi elaborado para comportar o slot "menu_ferramentas"
             */
            "bth-conta-usuario": LocalJSX.IntrinsicElements["bth-conta-usuario"] & JSXBase.HTMLAttributes<HTMLBthContaUsuarioElement>;
            "bth-empty-state": LocalJSX.IntrinsicElements["bth-empty-state"] & JSXBase.HTMLAttributes<HTMLBthEmptyStateElement>;
            "bth-icone": LocalJSX.IntrinsicElements["bth-icone"] & JSXBase.HTMLAttributes<HTMLBthIconeElement>;
            /**
             * Loader padrão com efeitos de animações
             */
            "bth-loader": LocalJSX.IntrinsicElements["bth-loader"] & JSXBase.HTMLAttributes<HTMLBthLoaderElement>;
            /**
             * Este componente exibe o logo da Betha e o nome do produto
             * Este componente foi elaborado para comportar o slot de "menu_marca_produto"
             */
            "bth-marca-produto": LocalJSX.IntrinsicElements["bth-marca-produto"] & JSXBase.HTMLAttributes<HTMLBthMarcaProdutoElement>;
            /**
             * Facilita a criação de Ferramentas para o menu. Abstrai comportamentos responsivos e controle do painel lateral.
             */
            "bth-menu-ferramenta": LocalJSX.IntrinsicElements["bth-menu-ferramenta"] & JSXBase.HTMLAttributes<HTMLBthMenuFerramentaElement>;
            /**
             * Abstrai a estilização de um ícone para menu-ferramenta.
             * Também implementa a possibilidade de exibição de um `badge` ao lado do ícone, através da propriedade `contador`.
             */
            "bth-menu-ferramenta-icone": LocalJSX.IntrinsicElements["bth-menu-ferramenta-icone"] & JSXBase.HTMLAttributes<HTMLBthMenuFerramentaIconeElement>;
            /**
             * Item que representa uma opção do menu para navegação horizontal
             */
            "bth-menu-horizontal-item": LocalJSX.IntrinsicElements["bth-menu-horizontal-item"] & JSXBase.HTMLAttributes<HTMLBthMenuHorizontalItemElement>;
            /**
             * Possibilita incluir conteúdo dinâmico em um painel lateral que sobrepõe o conteúdo da tela pela direita
             */
            "bth-menu-painel-lateral": LocalJSX.IntrinsicElements["bth-menu-painel-lateral"] & JSXBase.HTMLAttributes<HTMLBthMenuPainelLateralElement>;
            /**
             * Item que representa uma opção do menu para navegação vertical
             */
            "bth-menu-vertical-item": LocalJSX.IntrinsicElements["bth-menu-vertical-item"] & JSXBase.HTMLAttributes<HTMLBthMenuVerticalItemElement>;
            "bth-navbar-pill-group": LocalJSX.IntrinsicElements["bth-navbar-pill-group"] & JSXBase.HTMLAttributes<HTMLBthNavbarPillGroupElement>;
            "bth-navbar-pill-item": LocalJSX.IntrinsicElements["bth-navbar-pill-item"] & JSXBase.HTMLAttributes<HTMLBthNavbarPillItemElement>;
            "bth-notificacao-item": LocalJSX.IntrinsicElements["bth-notificacao-item"] & JSXBase.HTMLAttributes<HTMLBthNotificacaoItemElement>;
            "bth-notificacoes": LocalJSX.IntrinsicElements["bth-notificacoes"] & JSXBase.HTMLAttributes<HTMLBthNotificacoesElement>;
            "bth-novidade-item": LocalJSX.IntrinsicElements["bth-novidade-item"] & JSXBase.HTMLAttributes<HTMLBthNovidadeItemElement>;
            "bth-novidades": LocalJSX.IntrinsicElements["bth-novidades"] & JSXBase.HTMLAttributes<HTMLBthNovidadesElement>;
            "bth-pesquisa": LocalJSX.IntrinsicElements["bth-pesquisa"] & JSXBase.HTMLAttributes<HTMLBthPesquisaElement>;
            /**
             * Este componente permite compor uma lista de seleção de contexto.
             */
            "bth-selecao-contexto": LocalJSX.IntrinsicElements["bth-selecao-contexto"] & JSXBase.HTMLAttributes<HTMLBthSelecaoContextoElement>;
            /**
             * Componente do menu Suporte com Blip Chat
             * @see https://gitlab.services.betha.cloud/ped/tecnologia/nlp/blip-webchat-loader
             * @see https://gitlab.services.betha.cloud/ped/suite/atendimento/components/suite-atendimento
             */
            "bth-suporte": LocalJSX.IntrinsicElements["bth-suporte"] & JSXBase.HTMLAttributes<HTMLBthSuporteElement>;
            "bth-utilitarios": LocalJSX.IntrinsicElements["bth-utilitarios"] & JSXBase.HTMLAttributes<HTMLBthUtilitariosElement>;
        }
    }
}
